### PR TITLE
HEC-RAS_Controller_script

### PR DESCRIPTION
**Pull request by solomonvimal**
This script is being developed now. I am going to work on it to make it more presentable according to your file structure if necessary. For now it works independently, but requires manual installation of the libraries mentioned in the comment. 

I reported an error in your main branch earlier a week or two ago. The libraries you said would be installed from pip install pyras gave me an error message.

### CODE REVIEW

**Comment by goanpeca** [comment]
You uploaded two files... one without extension and the other with extension. Erase the one without extension and make everything PEP8 compatible

**Comment by goanpeca** [comment]
Why do you call it hecrascontroller? 

What functions do you need from the package to be able to use your functions?

The parsing functions should not depend on anything, they should be parsed by using the text files only

**Comment by goanpeca** [comment]
Why did you "redo" everything the luibrary is supposed to be doing? why not complete the functions in the library instead of doing this?

**Comment by solomonvimal** [comment]
I am doing this for a project and I thought it was easier for me to have
just one script and write it myself, so I know what all the functions do
precisely, instead of learning your implemented methods which are not
complete for now of all controller options...  and it's implementation
might take time because you plan to do it over a year. I also thought since
I am doing this now actively, it would be nice to develop this as a repo
and not just a script since there are some others who are interested in the
code, it's use and development.

The second file I put there is just an update, to see how files, I am
learning to use git hub on Windows in a gui.

**Comment by goanpeca** [comment]
If you want to add to this project then you should open a proper PR. This is not one.

**Comment by solomonvimal** [comment]
What's PR?

**Comment by goanpeca** [comment]
Pull Request

**Pull request closed without merging**
